In [7]:
#1. Import the NUMPY package under the name np.

#[your code here]
import numpy as np

In [8]:
#2. Print the NUMPY version and the configuration.

#[your code here]
print("Numpy version: ", np.__version__)

np.show_config()

Numpy version:  1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/envs/original/include
    lib directory: /opt/anaconda3/envs/original/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/envs/original/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/envs/original/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_bas

In [9]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

#[your code here]

a = np.random.randint(10, size=(2, 3, 5))

#4. Print a.
print(a)


[[[2 0 7 9 8]
  [7 2 5 8 4]
  [5 8 9 1 3]]

 [[8 7 4 6 1]
  [0 9 4 5 4]
  [5 1 5 3 0]]]


In [10]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

#[your code here]
b = np.ones((5, 2, 3), dtype=int)

#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [11]:
#7. Do a and b have the same size? How do you prove that in Python code?
#[your code here]
print(a.size)
print(b.size)

np.size(a) == np.size(b)


30
30


True

In [12]:
#8. Are you able to add a and b? Why or why not?

#[your code here]
# tienen el mismo size pero no el mismo shape, con diferente shape no se pueden sumar
print(np.shape(a))
print(np.shape(b))

(2, 3, 5)
(5, 2, 3)


In [13]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

#[your code here]
#c = np.reshape(b, (2, 3, 5))   
c = b.reshape((2, 3, 5))
print(c)


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [14]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

#[your code here]
d = np.array(a) + np.array(c)
print(d)
# funciona porque tienen el mismo shape (2,3,5)

[[[ 3  1  8 10  9]
  [ 8  3  6  9  5]
  [ 6  9 10  2  4]]

 [[ 9  8  5  7  2]
  [ 1 10  5  6  5]
  [ 6  2  6  4  1]]]


In [15]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

#[your code here]
print(a)
print(d)
# el array d son los números del array a +1 (porque el array c era de solo 1s)

[[[2 0 7 9 8]
  [7 2 5 8 4]
  [5 8 9 1 3]]

 [[8 7 4 6 1]
  [0 9 4 5 4]
  [5 1 5 3 0]]]
[[[ 3  1  8 10  9]
  [ 8  3  6  9  5]
  [ 6  9 10  2  4]]

 [[ 9  8  5  7  2]
  [ 1 10  5  6  5]
  [ 6  2  6  4  1]]]


In [16]:
#12. Multiply a and c. Assign the result to e.

#[your code here]
e = np.array(a) * np.array(c)
print(e)

[[[2 0 7 9 8]
  [7 2 5 8 4]
  [5 8 9 1 3]]

 [[8 7 4 6 1]
  [0 9 4 5 4]
  [5 1 5 3 0]]]


In [17]:
#13. Does e equal to a? Why or why not?

#[your code here]
np.array(a) == np.array(e)
# como la multiplicación de cualquier número por 1 da el mismo elemento, 
# pues el array e es igual al array a porque es la multiplicación de cada elemento de a por 1


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [18]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

#[your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

10
1
5.666666666666667


In [20]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

#[your code here]
f = np.zeros_like(d)
print(f)
print(d)
# comentario para mi
# print(d.shape[2]) #shape of d (2,3,5) / segùn el indice me dice la dimensión, las filas o las columnas


[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
[[[ 3  1  8 10  9]
  [ 8  3  6  9  5]
  [ 6  9 10  2  4]]

 [[ 9  8  5  7  2]
  [ 1 10  5  6  5]
  [ 6  2  6  4  1]]]
5


In [22]:
h = np.zeros((2, 3, 5), dtype = int)
print(h)


[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [21]:
g = np.empty((2, 3, 5), dtype = int)
print(g)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [23]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

#[your code here]
for i in range(d.shape[0]):
    for k in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[i][k][z] > d_mean and d[i][k][z] < d_max:
                f[i][k][z] = 75
            elif d[i][k][z] == d_mean:
                f[i][k][z] = 50
            elif d[i][k][z] == d_min:
                f[i][k][z] = 0
            elif d[i][k][z] == d_max:
                f[i][k][z] = 100
            elif d[i][k][z] > d_min and d[i][k][z] < d_mean:
                f[i][k][z] = 25

print(f)
print(d)

[[[ 25   0  75 100  75]
  [ 75  25  75  75  25]
  [ 75  75 100  25  25]]

 [[ 75  75  25  75  25]
  [  0 100  25  75  25]
  [ 75  25  75  25   0]]]
[[[ 3  1  8 10  9]
  [ 8  3  6  9  5]
  [ 6  9 10  2  4]]

 [[ 9  8  5  7  2]
  [ 1 10  5  6  5]
  [ 6  2  6  4  1]]]


In [25]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

#[your code here]
print(d)
print(f)

[[[ 3  1  8 10  9]
  [ 8  3  6  9  5]
  [ 6  9 10  2  4]]

 [[ 9  8  5  7  2]
  [ 1 10  5  6  5]
  [ 6  2  6  4  1]]]
[[[ 25   0  75 100  75]
  [ 75  25  75  75  25]
  [ 75  75 100  25  25]]

 [[ 75  75  25  75  25]
  [  0 100  25  75  25]
  [ 75  25  75  25   0]]]


In [26]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

#[your code here] 
s = np.empty((2, 3, 5), dtype = str)
for i in range(d.shape[0]):
    for k in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[i][k][z] > d_mean and d[i][k][z] < d_max:
                s[i][k][z] = "D"
            elif d[i][k][z] == d_mean:
                s[i][k][z] = "C"
            elif d[i][k][z] == d_min:
                s[i][k][z] = "A"
            elif d[i][k][z] == d_max:
                s[i][k][z] = "E"
            elif d[i][k][z] > d_min and d[i][k][z] < d_mean:
                s[i][k][z] = "B"

print(s)

[[['B' 'A' 'D' 'E' 'D']
  ['D' 'B' 'D' 'D' 'B']
  ['D' 'D' 'E' 'B' 'B']]

 [['D' 'D' 'B' 'D' 'B']
  ['A' 'E' 'B' 'D' 'B']
  ['D' 'B' 'D' 'B' 'A']]]
