In [2]:
#1. Import the NUMPY package under the name np.

#[your code here]
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.

#[your code here]
print("Numpy version: ", np.__version__)

Numpy version:  1.26.4


In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

#[your code here]

a = np.random.randint(10, size=(2, 3, 5))

#4. Print a.
print(a)


[[[7 4 7 0 2]
  [1 8 0 0 7]
  [5 9 2 2 3]]

 [[5 9 8 8 1]
  [1 2 6 6 7]
  [8 1 5 2 9]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

#[your code here]
b = np.ones((5, 2, 3), dtype=int)

#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [6]:
#7. Do a and b have the same size? How do you prove that in Python code?
#[your code here]
print(a.size)
print(b.size)

np.size(a) == np.size(b)


30
30


True

In [7]:
#8. Are you able to add a and b? Why or why not?

#[your code here]
# tienen el mismo size pero no el mismo shape
print(np.shape(a))
print(np.shape(b))

(2, 3, 5)
(5, 2, 3)


In [8]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

#[your code here]
#c = np.reshape(b, (2, 3, 5))   
c = b.reshape((2, 3, 5))
print(c)


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [9]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

#[your code here]
d = np.array(a) + np.array(c)
print(d)
# funciona porque tienen el mismo shape (2,3,5)

[[[ 8  5  8  1  3]
  [ 2  9  1  1  8]
  [ 6 10  3  3  4]]

 [[ 6 10  9  9  2]
  [ 2  3  7  7  8]
  [ 9  2  6  3 10]]]


In [10]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

#[your code here]
print(a)
print(d)
# el array d son los números del array a +1 (porque el array c era de solo 1s)

[[[7 4 7 0 2]
  [1 8 0 0 7]
  [5 9 2 2 3]]

 [[5 9 8 8 1]
  [1 2 6 6 7]
  [8 1 5 2 9]]]
[[[ 8  5  8  1  3]
  [ 2  9  1  1  8]
  [ 6 10  3  3  4]]

 [[ 6 10  9  9  2]
  [ 2  3  7  7  8]
  [ 9  2  6  3 10]]]


In [11]:
#12. Multiply a and c. Assign the result to e.

#[your code here]
e = np.array(a) * np.array(c)
print(e)

[[[7 4 7 0 2]
  [1 8 0 0 7]
  [5 9 2 2 3]]

 [[5 9 8 8 1]
  [1 2 6 6 7]
  [8 1 5 2 9]]]


In [12]:
#13. Does e equal to a? Why or why not?

#[your code here]
np.array(a) == np.array(e)
# como la multiplicación de cualquier número por 1 da el mismo elemento, 
# pues el array e es igual al array a porque es la multiplicación de cada elemento de a por 1


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [13]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

#[your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

10
1
5.5


In [14]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

#[your code here]
f = np.zeros_like(d)
print(f)
print(d)
print(d.shape[0]) #shape of d (2,3,5)


[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
[[[ 8  5  8  1  3]
  [ 2  9  1  1  8]
  [ 6 10  3  3  4]]

 [[ 6 10  9  9  2]
  [ 2  3  7  7  8]
  [ 9  2  6  3 10]]]
2


In [15]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

#[your code here]
for i in range(d.shape[0]):
    for k in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[i][k][z] > d_mean and d[i][k][z] < d_max:
                f[i][k][z] = 75
            elif d[i][k][z] == d_mean:
                f[i][k][z] = 50
            elif d[i][k][z] == d_min:
                f[i][k][z] = 0
            elif d[i][k][z] == d_max:
                f[i][k][z] = 100
            elif d[i][k][z] > d_min and d[i][k][z] < d_mean:
                f[i][k][z] = 25

print(f)

[[[ 75  25  75   0  25]
  [ 25  75   0   0  75]
  [ 75 100  25  25  25]]

 [[ 75 100  75  75  25]
  [ 25  25  75  75  75]
  [ 75  25  75  25 100]]]


In [17]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

#[your code here]
print(d)
print(f)

[[[ 8  5  8  1  3]
  [ 2  9  1  1  8]
  [ 6 10  3  3  4]]

 [[ 6 10  9  9  2]
  [ 2  3  7  7  8]
  [ 9  2  6  3 10]]]
[[[ 75  25  75   0  25]
  [ 25  75   0   0  75]
  [ 75 100  25  25  25]]

 [[ 75 100  75  75  25]
  [ 25  25  75  75  75]
  [ 75  25  75  25 100]]]


In [18]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

#[your code here] 
for i in range(d.shape[0]):
    for k in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[i][k][z] > d_mean and d[i][k][z] < d_max:
                f[i][k][z] = "D"
            elif d[i][k][z] == d_mean:
                f[i][k][z] = "C"
            elif d[i][k][z] == d_min:
                f[i][k][z] = "A"
            elif d[i][k][z] == d_max:
                f[i][k][z] = "E"
            elif d[i][k][z] > d_min and d[i][k][z] < d_mean:
                f[i][k][z] = "B"

print(f)

ValueError: invalid literal for int() with base 10: 'D'